#!/bin/bash
VAULT_VERSION=0.1.0
VAULT_FILE=vault_${VAULT_VERSION}_linux_amd64.zip
VAULT_URL=https://dl.bintray.com/mitchellh/vault/${VAULT_FILE}
DOCKER_VAULT_IMAGE=dontrebootme/vault:${VAULT_VERSION}

curl -sLOk ${VAULT_URL} \
  && unzip -o ${VAULT_FILE} \
  && docker build --rm=true --no-cache=true --pull=true -t ${DOCKER_VAULT_IMAGE} . \
  && echo "Now pushing ${DOCKER_VAULT_IMAGE}" \
  && docker push ${DOCKER_VAULT_IMAGE} \
  && echo "Done. You may now start up the container."
